openapi: 3.0.0
info:
  version: '1.0'
  title: apiapi
  description: Api that gets apis
paths:
  /:
    get:
      tags:
        - Général
      summary: Message de bienvenue
      responses:
        '200': 
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                example:
                    success: true
                    message : 'Hello world!'
  /apis:
    get:
      tags:
        - Apis
      summary: Retourne toutes les apis
      responses:
        '200' :
          description: Toutes les apis existantes
    post:
      tags: 
        - Apis
      summary: Création d'un api.
      requestBody:
        description: Les informations de l'api à créer
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
                description:
                  type: string
              example:
                name : 'TheApiApi'
                url: 'https://theapi.api/apis'
                description: 'Api that gives apis'
      responses:
        '201': 
          description: "L'id de l'api créé"
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                example:
                  id : 1
        '400': 
          description: "Des informations sont manquantes"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  url:
                    type: string
                  description:
                    type: string
                example:
                  description : "Description is required"
  /apis/{ID}:
    delete:
      parameters:
        - in: path
          name: ID
          schema:
            type: integer
          required: true
          description: ID de l'api à supprimer
      tags: 
        - Apis
      summary: Supression d'un api
      responses:
        '204':
          description: L'api à été supprimée
        '401': 
          description: "Les information de connection sont invalides"
          content:
            application/json:
              schema:
                type: object
                example:
                   User was not authentified: "Invalid user credentials"
        '404': 
          description: "L'id est invalide"
    put:
      parameters:
        - in: path
          name: ID
          schema:
            type: integer
          required: true
          description: ID de l'api à modifier
      requestBody:
        description: Les informations de l'api à créer
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
                description:
                  type: string
              example:
                name : 'TheApiApi'
                url: 'https://theapi.api/apis'
                description: 'Api that gives apis'
      tags: 
        - Apis
      summary: Modification d'un api
      responses:
        '204':
          description: L'api à été modifiée
        '400': 
          description: "Des informations sont manquantes ou l'id est invalide"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  url:
                    type: string
                  description:
                    type: string
                  id:
                    type: integer
                example:
                  description : "Description is required"