-- libapi.books definition

CREATE TABLE `books` (
  `id` int DEFAULT NULL,
  `title` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `link` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `series` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `cover_link` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `author` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `author_link` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `rating_count` int DEFAULT NULL,
  `review_count` int DEFAULT NULL,
  `average_rating` double DEFAULT NULL,
  `five_star_ratings` int DEFAULT NULL,
  `four_star_ratings` int DEFAULT NULL,
  `three_star_ratings` int DEFAULT NULL,
  `two_star_ratings` int DEFAULT NULL,
  `one_star_ratings` int DEFAULT NULL,
  `number_of_pages` int DEFAULT NULL,
  `date_published` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `publisher` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `original_title` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `genre_and_votes` varchar(512) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `isbn` varchar(16) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `isbn13` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `asin` varchar(16) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `settings` text COLLATE utf8mb4_general_ci,
  `characters` varchar(2048) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `awards` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `amazon_redirect_link` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `worldcat_redirect_link` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `recommended_books` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `books_in_series` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `description` blob
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;